# Generated by Django 5.2.5 on 2025-08-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reserve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(blank=True)),
                ("nationality_id", models.CharField(blank=True, max_length=10)),
                ("phone_number", models.CharField(max_length=11)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
            ],
        ),
    ]
