# Generated by Django 5.2.5 on 2025-08-17 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Reserve",
            new_name="Reservation",
        ),
    ]
