# Generated by Django 5.2.5 on 2025-08-17 17:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0002_rename_reserve_reservation"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="datetime_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
