# Generated by Django 5.2.5 on 2025-08-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0004_alter_reservation_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="nationality_id",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="phone_number",
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="reservation",
            unique_together={("nationality_id", "phone_number")},
        ),
    ]
