# Generated by Django 5.2.5 on 2025-08-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0005_alter_reservation_nationality_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="full_name",
            field=models.CharField(),
        ),
    ]
