# Generated by Django 5.2.5 on 2025-08-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0007_alter_reservation_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="time",
            field=models.CharField(
                choices=[
                    ("FirstT", "7-8"),
                    ("SecT", "8-9"),
                    ("ThiT", "9-10"),
                    ("ForT", "10-11"),
                    ("FifT", "11-12"),
                    ("SixT", "14-15"),
                    ("LastT", "15-16"),
                ],
                default="7-8",
                max_length=6,
            ),
        ),
    ]
