# Generated by Django 5.2.5 on 2025-08-17 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0008_alter_reservation_time"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="reservation",
            unique_together={("date", "time"), ("nationality_id", "phone_number")},
        ),
    ]
