# Generated by Django 5.2.5 on 2025-08-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0009_alter_reservation_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="time",
            field=models.CharField(
                choices=[
                    ("7-8", "7-8"),
                    ("8-9", "8-9"),
                    ("9-10", "9-10"),
                    ("10-11", "10-11"),
                    ("11-12", "11-12"),
                    ("14-15", "14-15"),
                    ("15-16", "15-16"),
                ],
                default="7-8",
                max_length=6,
            ),
        ),
    ]
