# Generated by Django 5.2.5 on 2025-08-18 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0010_alter_reservation_time"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="reservation",
            unique_together={("nationality_id", "phone_number"), ("time", "date")},
        ),
    ]
